### ISSUE TITLE
Compilation error in ‘bool WebCore::isValidNameNonASCII’

### ISSUE THREAD

**Issue by tarnh** [qtwebkit/qtwebkit#926]
I'm getting errors because of missing semicolons in ‘bool WebCore::isValidNameNonASCII(const UChar*, unsigned int)’ when compiling qtwebkit from [ArchLinux](https://www.archlinux.org/packages/extra/x86_64/qt5-webkit/).

Here is my full error log: https://pastebin.com/CEpsQXT1

**Comment by annulen** [comment]
This patch is needed for alpha3 to build with ICU 65.1: dc02ec4080010e33b737db6491d71d6bb961a77d
