### ISSUE TITLE
fatal error: XPathGrammar.hpp: No such file or directory

### ISSUE THREAD

**Issue by leimaohui** [qtwebkit/qtwebkit#1023]
With latest poky, qtwebkit build failed:

`/test-dev/test002/build-test/test-202009/build-test-armv8-multlib/tmp/work/aarch64-test-linux/qtwebkit/5.15.0+gitAUTOINC+10cd6a106e-r0/build/DerivedSources/WebCore/XPathGrammar.cpp:120:10: fatal error: XPathGrammar.hpp: No such file or directory
  120 | #include "XPathGrammar.hpp"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.`

Is it because newest bison?

**Comment by kth5** [comment]
Same happens on ppc64le:

`-- Using platform-specific CMakeLists: /build/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/PlatformQt.cmake
-- Using platform-specific CMakeLists: /build/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/PlatformQt.cmake
-- Using platform-specific CMakeLists: /build/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/shell/PlatformQt.cmake
-- All-in-One build is enabled.
-- Using platform-specific CMakeLists: /build/src/qtwebkit-5.212.0-alpha4/Source/WebCore/PlatformQt.cmake
-- Using platform-specific CMakeLists: /build/src/qtwebkit-5.212.0-alpha4/Source/WebKit/PlatformQt.cmake
-- Using platform-specific CMakeLists: /build/src/qtwebkit-5.212.0-alpha4/Source/WebKit2/PlatformQt.cmake
-- Using platform-specific CMakeLists: /build/src/qtwebkit-5.212.0-alpha4/Source/PlatformQt.cmake
-- Enabled features:
--  ENABLE_ACCELERATED_2D_CANVAS ............ ON
--  ENABLE_ALLINONE_BUILD                     ON
--  ENABLE_API_TESTS ........................ ON
--  ENABLE_CSS_GRID_LAYOUT                    ON
--  ENABLE_DATABASE_PROCESS ................. ON
--  ENABLE_DATALIST_ELEMENT                   ON
--  ENABLE_DEVICE_ORIENTATION ............... ON
--  ENABLE_DRAG_SUPPORT                       ON
--  ENABLE_FULLSCREEN_API ................... ON
--  ENABLE_GAMEPAD_DEPRECATED                 ON
--  ENABLE_GEOLOCATION ...................... ON
--  ENABLE_ICONDATABASE                       ON
--  ENABLE_INDEXED_DATABASE ................. ON
--  ENABLE_INSPECTOR_UI                       ON
--  ENABLE_JIT .............................. OFF
--  ENABLE_LEGACY_WEB_AUDIO                   ON
--  ENABLE_LINK_PREFETCH .................... ON
--  ENABLE_MEDIA_SOURCE                       ON
--  ENABLE_NETSCAPE_PLUGIN_API .............. ON
--  ENABLE_OPENGL                             ON
--  ENABLE_PRINT_SUPPORT .................... ON
--  ENABLE_QT_GESTURE_EVENTS                  ON
--  ENABLE_QT_WEBCHANNEL .................... ON
--  ENABLE_SAMPLING_PROFILER                  OFF
--  ENABLE_SPELLCHECK ....................... ON
--  ENABLE_TOUCH_EVENTS                       ON
--  ENABLE_VIDEO ............................ ON
--  ENABLE_WEBKIT2                            ON
--  ENABLE_WEB_AUDIO ........................ ON
--  ENABLE_X11_TARGET                         ON
--  ENABLE_XSLT ............................. ON
--  USE_GSTREAMER                             ON
--  USE_LIBHYPHEN ........................... ON
--  USE_LIBJPEG                               ON
--  USE_MEDIA_FOUNDATION .................... OFF
--  USE_QT_MULTIMEDIA                         OFF
--  USE_SYSTEM_MALLOC ....................... OFF
--  USE_WOFF2                                 ON
-- Configuring done
-- Generating done
-- Build files have been written to: /build/src/build
[  1%] Built target stageSharedScripts
[  1%] Built target bmalloc
[  1%] Built target qmlwebkitexperimentalplugin-files
[  1%] Built target qmlwebkitplugin-files
[  3%] Built target ANGLESupport
[  4%] Built target WTF
[  4%] Built target gtest
[  4%] Built target LLIntOffsetsExtractor
[  4%] Built target WebKit2-forwarding-headers
[ 22%] Built target JavaScriptCore
[ 22%] Built target testair
[ 22%] Built target testb3
[ 22%] Built target jsc
[ 22%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/XPathGrammar.cpp.o
[ 22%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/CSSGrammar.cpp.o
[ 22%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/JSCoordinates.cpp.o
[ 22%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/JSGeolocation.cpp.o
[ 22%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/JSGeoposition.cpp.o
[ 22%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/JSNavigatorGeolocation.cpp.o
[ 22%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/JSPositionCallback.cpp.o
[ 22%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/JSPositionError.cpp.o
[ 22%] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/JSPositionErrorCallback.cpp.o
/build/src/build/DerivedSources/WebCore/XPathGrammar.cpp:120:10: fatal error: XPathGrammar.hpp: No such file or directory
  120 | #include "XPathGrammar.hpp"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Source/WebCore/CMakeFiles/WebCore.dir/build.make:28201: Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/XPathGrammar.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/build/src/build/DerivedSources/WebCore/CSSGrammar.cpp:160:10: fatal error: CSSGrammar.hpp: No such file or directory
  160 | #include "CSSGrammar.hpp"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Source/WebCore/CMakeFiles/WebCore.dir/build.make:28188: Source/WebCore/CMakeFiles/WebCore.dir/__/__/DerivedSources/WebCore/CSSGrammar.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1531: Source/WebCore/CMakeFiles/WebCore.dir/all] Error 2
make: *** [Makefile:182: all] Error 2`

Can provide more logs on request.

**Comment by annulen** [comment]
Does it happen with Ninja generator (add "-G NInja" to cmake arguments)?

**Comment by kth5** [comment]
> Does it happen with Ninja generator (add "-G NInja" to cmake arguments)?

Indeed, it does still fail with the same error. It also has one additional file it looks for. It doesn't necessary reveal itself with multi-core builds. (-j>1)

Instances:
`
DerivedSources/WebCore/CSSGrammar.cpp:160:10: fatal error: CSSGrammar.hpp: No such file or directory
`

**Comment by kth5** [comment]
Downgrading from bison 3.7.2 to 3.6.4 seems to have fixed builds with make and ninja.

**Comment by leimaohui** [comment]
This issue has gone with the following patch:

```
commit 04a6fa63cf3148698a52b207058254b01c6937b1
Author: Andreas Müller <schnitzeltony@gmail.com>
Date:   Mon Sep 7 22:55:43 2020 +0200

    qtwebkit: Add patch to fix build with bison 3.7
......
```

**Comment by annulen** [comment]
Fixed in d92b11fea65364fefa700249bd3340e0cd4c5b31
