### ISSUE TITLE
Build failure with glib 2.68

### ISSUE THREAD

**Issue by rezso** [qtwebkit/qtwebkit#1057]
Build with glib 2.68 fails:

`In file included from /usr/lib/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/gstreamer-1.0/gst/gst.h:27,
                 from ../Source/WebCore/platform/graphics/gstreamer/GStreamerUtilities.h:21,
                 from ../Source/WebCore/platform/graphics/gstreamer/GStreamerUtilities.cpp:23:
../Source/WTF/wtf/glib/GRefPtr.h:33:21: error: expected unqualified-id before ‘typename’
   33 | extern "C" gpointer g_object_ref_sink(gpointer);
      |                     ^~~~~~~~~~~~~~~~~
../Source/WTF/wtf/glib/GRefPtr.h:33:21: error: expected ‘)’ before ‘typename’
In file included from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/gstreamer-1.0/gst/gstenumtypes.h:6,
                 from /usr/include/gstreamer-1.0/gst/gst.h:31,
                 from ../Source/WebCore/platform/graphics/gstreamer/GStreamerUtilities.h:21,
                 from ../Source/WebCore/platform/graphics/gstreamer/GStreamerUtilities.cpp:23:
../Source/WTF/wtf/glib/GRefPtr.h:33:21: note: to match this ‘(’
   33 | extern "C" gpointer g_object_ref_sink(gpointer);
      |                     ^~~~~~~~~~~~~~~~~
In file included from /usr/lib/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/gstreamer-1.0/gst/gst.h:27,
                 from ../Source/WebCore/platform/graphics/gstreamer/GStreamerUtilities.h:21,
                 from ../Source/WebCore/platform/graphics/gstreamer/GStreamerUtilities.cpp:23:
../Source/WTF/wtf/glib/GRefPtr.h:33:21: error: expected ‘)’ before ‘typename’
   33 | extern "C" gpointer g_object_ref_sink(gpointer);
      |                     ^~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/gstreamer-1.0/gst/gstenumtypes.h:6,
                 from /usr/include/gstreamer-1.0/gst/gst.h:31,
                 from ../Source/WebCore/platform/graphics/gstreamer/GStreamerUtilities.h:21,
                 from ../Source/WebCore/platform/graphics/gstreamer/GStreamerUtilities.cpp:23:
../Source/WTF/wtf/glib/GRefPtr.h:33:21: note: to match this ‘(’
   33 | extern "C" gpointer g_object_ref_sink(gpointer);
      |                     ^~~~~~~~~~~~~~~~~
`

Removing `extern "C" void g_object_unref(gpointer);` and `extern "C" gpointer g_object_ref_sink(gpointer);` from Source/WTF/wtf/glib/GRefPtr.h solves this error.

**Comment by Vogtinator** [comment]
This is an issue with WebKit, not QtWebKit specifically.

**Comment by Vogtinator** [comment]
It looks like upstream WebKit is very lucky and inches around the problem by a different order of includes. In current qtwebkit, `gst.h` is included first (which includes gobject), then `GRefPtr.h`. Since https://github.com/WebKit/WebKit/commit/ed1f9bca2ca72a8ccc4450380864059f5b1f1ca2#diff-bd775e5dd224606dbeab641c083995ae189e80528a1ffaa19cc1dc66be3e9501, upstream has it the other way around, so the declarations aren't malformed at that point.

**Comment by annulen** [comment]
@mnutt This issue is still relevant in master:
```
/usr/bin/ccache /usr/lib/llvm/16/bin/clang++ -DBUILDING_QT__=1 -DBUILDING_WEBKIT=1 -DBUILDING_WITH_CMAKE=1 -DBUILDING_WebCore -DHAVE_CONFIG_H=1 -DPAS_BMALLOC=1 -DQT_ASCII_CAST_WARNINGS -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DYNAMIC_CAST -DQT_NO_EXCEPTIONS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DSTATICALLY_LINKED_WITH_JavaScriptCore -DSTATICALLY_LINKED_WITH_PAL -DSTATICALLY_LINKED_WITH_WTF -DSTATICALLY_LINKED_WITH_bmalloc ... -c /home/ktokarev/WebKit/qtwebkit-dev-2/Source/WebCore/platform/graphics/gstreamer/ImageGStreamerQt.cpp
In file included from /home/ktokarev/WebKit/qtwebkit-dev-2/Source/WebCore/platform/graphics/gstreamer/ImageGStreamerQt.cpp:21:
In file included from /home/ktokarev/WebKit/qtwebkit-dev-2/Source/WebCore/platform/graphics/gstreamer/ImageGStreamer.h:26:
In file included from /home/ktokarev/WebKit/qtwebkit-dev-2/Source/WebCore/platform/graphics/gstreamer/GStreamerCommon.h:24:
In file included from /home/ktokarev/WebKit/qtwebkit-dev-2/Source/WebCore/platform/graphics/gstreamer/GRefPtrGStreamer.h:26:
/home/ktokarev/WebKit/qtwebkit-dev-2/build/host-clang/WTF/Headers/wtf/glib/GRefPtr.h:38:21: error: expected unqualified-id
extern "C" gpointer g_object_ref_sink(gpointer);
                    ^
/usr/include/glib-2.0/gobject/gobject.h:549:34: note: expanded from macro 'g_object_ref_sink'
#define g_object_ref_sink(Obj) ((glib_typeof (Obj)) (g_object_ref_sink) (Obj))
                                 ^
/usr/include/glib-2.0/glib/glib-typeof.h:44:24: note: expanded from macro 'glib_typeof'
#define glib_typeof(t) typename std::remove_reference<decltype (t)>::type
                       ^
```

**Comment by mnutt** [comment]
I don't currently have easy access to a dev machine that runs linux with glib 2.68+, but am going to enable GitHub Actions to run there and try to reproduce the issue.

**Comment by mnutt** [comment]
Fixed in my fork via https://github.com/movableink/webkit/pull/9

**Comment by Vogtinator** [comment]
Note also https://github.com/qtwebkit/qtwebkit/pull/1058

**Comment by FabioLolix** [comment]
On AUR qt5-webkit pkgbuild https://aur.archlinux.org/packages/qt5-webkit is fixed by https://aur.archlinux.org/cgit/aur.git/tree/glib-2.68.patch?h=qt5-webkit

**Comment by annulen** [comment]
But I guess we all can agree that this is not a real fix of an issue with forward declarations, just a workaround.

It seems to me that the real bug is include order in `GRefPtrGStreamer.h`, where `#include <gst/gst.h>` is done before `#include <wtf/glib/GRefPtr.h>`. This order originates from ordering suggested by WebKit coding style, but it simply cannot work unless `GRefPtr.h` is already included by user of `GRefPtrGStreamer.h`.
```diff
diff --git a/Source/WebCore/platform/graphics/gstreamer/GRefPtrGStreamer.h b/Source/WebCore/platform/graphics/gstreamer/GRefPtrGStreamer.h
index 1588a813b5d3..3f06a4571e58 100644
--- a/Source/WebCore/platform/graphics/gstreamer/GRefPtrGStreamer.h
+++ b/Source/WebCore/platform/graphics/gstreamer/GRefPtrGStreamer.h
@@ -21,9 +21,9 @@
 
 #if USE(GSTREAMER)
 
+#include <wtf/glib/GRefPtr.h>
 #include <gst/gst.h>
 #include <gst/pbutils/encoding-profile.h>
-#include <wtf/glib/GRefPtr.h>
 
 typedef struct _WebKitVideoSink WebKitVideoSink;
 struct WebKitWebSrc;
```
I guess GTK and WPE are building fine only because they use GRefPtr more extensively and it gets included earlier.

**Comment by annulen** [comment]
@philn: How do you think, would it be OK to change include order in `GRefPtrGStreamer.h` like show in a previous comment? See justification above.

**Comment by philn** [comment]
Yes, and an exception for build/include_order should be added for this file in the style checker...
